[toolchain]
anchor_version = "0.30.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_protocol = "9CoY42r3y5WFDJjQX97e9m9THcVGpvuVSKjBjGkiksMR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
