[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_protocol = "H3nXZdjSdx4UwaeKRR2o2v6whsRCoKyrbLvDBMCViUD9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
